title: Material Motion
email: material-motion@googlegroups.com
description: "Exploring solutions that will empower creators with the tools needed to describe and implement rich, interactive motion on any platform."
baseurl: ""
url: "https://material-motion.github.io/material-motion"
icon: "material-motion.png"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

toc:
  - page:
    title: "Starmap"
    url: "/starmap"
    children:
     - page:
       title: "Overview"
       url: "/starmap/overview"
     - page:
       title: "Engineering spec"
       url: "/starmap/specifications/"
       children:
        - page:
          title: "Motion primitives"
          url: "/starmap/specifications/primitives"
          children:
            - page:
              title: "How to connect primitives"
              url: "/starmap/specifications/how_to_connect_primitives"
        - page:
          title: "Declarative motion"
          url: "/starmap/specifications/pattern"
        - page:
          title: "Motion runtime"
          url: "/starmap/specifications/runtime/"
          children:
            - page:
              title: "Life of a plan"
              url: "/starmap/specifications/runtime/life_of_a_plan"
            - page:
              title: "Plan"
              url: "/starmap/specifications/runtime/plan"
            - page:
              title: "Performer"
              url: "/starmap/specifications/runtime/performer"
              children:
                - page:
                  title: "Feature: composition"
                  url: "/starmap/specifications/runtime/performer-composition"
            - page:
              title: "Runtime"
              url: "/starmap/specifications/runtime/runtime"
              children:
                - page:
                  title: "Feature: tracing"
                  url: "/starmap/specifications/runtime/runtime_tracing"
            - page:
              title: "Feature: named plans"
              url: "/starmap/specifications/runtime/named-plans"
            - page:
              title: "Feature: target selectors"
              url: "/starmap/specifications/runtime/target_selectors"
        - page:
          title: "Motion language"
          url: "/starmap/specifications/plans/"
          children:
            - page:
              title: "📝 ArcMove"
              url: "/starmap/specifications/plans/ArcMove"
            - page:
              title: "📝 BasicTween"
              url: "/starmap/specifications/plans/BasicTween"
            - page:
              title: "🚩 ChangeAnchorPoint"
              url: "/starmap/specifications/plans/ChangeAnchorPoint"
            - page:
              title: "🚩 DirectlyManipulable"
              url: "/starmap/specifications/plans/DirectlyManipulable"
            - page:
              title: "🚩 Draggable"
              url: "/starmap/specifications/plans/Draggable"
            - page:
              title: "🚩 Pinchable"
              url: "/starmap/specifications/plans/Pinchable"
            - page:
              title: "📢  RemoveSpring"
              url: "/starmap/specifications/plans/RemoveSpring"
            - page:
              title: "🚩 Rotatable"
              url: "/starmap/specifications/plans/Rotatable"
            - page:
              title: "📝 ScrollReactor"
              url: "/starmap/specifications/plans/ScrollReactor"
            - page:
              title: "🚩 SpringTo"
              url: "/starmap/specifications/plans/SpringTo"
            - page:
              title: "🚩 TransitionTween"
              url: "/starmap/specifications/plans/TransitionTween"
            - page:
              title: "🚩 Tween"
              url: "/starmap/specifications/plans/Tween"
            - page:
              title: "📝 VelocitySource"
              url: "/starmap/specifications/plans/VelocitySource"
        - page:
          title: "Motion library"
          url: "/starmap/specifications/motion_library"
        - page:
          title: "Interactions"
          url: "/starmap/specifications/interactions/"
          children:
            - page:
              title: "Director"
              url: "/starmap/specifications/interactions/director"
            - page:
              title: "Transitions"
              url: "/starmap/specifications/interactions/transitions/"
              children:
                - page:
                  title: "Directionality"
                  url: "/starmap/specifications/interactions/transitions/directionality"
                - page:
                  title: "Time window"
                  url: "/starmap/specifications/interactions/transitions/time_window"
                - page:
                  title: "Time window segment"
                  url: "/starmap/specifications/interactions/transitions/time_window_segment"
                - page:
                  title: "Life of a transition director"
                  url: "/starmap/specifications/interactions/transitions/life_of_a_transition_director"
                - page:
                  title: "Transition"
                  url: "/starmap/specifications/interactions/transitions/Transition"
                  children:
                    - page:
                      title: "Feature: context element"
                      url: "/starmap/specifications/interactions/transitions/feature_context_element"
                    - page:
                      title: "Feature: interruptible"
                      url: "/starmap/specifications/interactions/transitions/feature_interruptible"
                - page:
                  title: "TransitionDirector"
                  url: "/starmap/specifications/interactions/transitions/TransitionDirector"
                  children:
                    - page:
                      title: "Feature: transition preconditions"
                      url: "/starmap/specifications/interactions/transitions/feature_transition_preconditions"
                    - page:
                      title: "Feature: replication"
                      url: "/starmap/specifications/interactions/transitions/feature_replication"
                - page:
                  title: "Platform: iOS"
                  url: "/starmap/specifications/interactions/transitions/platform/ios/"
                  children:
                    - page:
                      title: "Life of a transition controller"
                      url: "/starmap/specifications/interactions/transitions/platform/ios/life_of_a_transition_controller"
                    - page:
                      title: "TransitionController"
                      url: "/starmap/specifications/interactions/transitions/platform/ios/TransitionController"
                      children:
                        - page:
                          title: "Feature: director stack"
                          url: "/starmap/specifications/interactions/transitions/platform/ios/feature_director_stack"
        - page:
          title: "Target replication"
          url: "/starmap/specifications/replicas"
          children:
            - page:
              title: "ReplicaController"
              url: "/starmap/specifications/replicator_controller"
            - page:
              title: "ReplicaControllerDelegate"
              url: "/starmap/specifications/replicator"
        - page:
          title: "Domain mapping"
          url: "/starmap/specifications/runtime/feature_nested_timelines"
     - page:
       title: "User journeys"
       url: "/starmap/user_journeys/"
       children:
        - page:
          title: "Motion"
          url: "/starmap/user_journeys/motion"
        - page:
          title: "Engineering"
          url: "/starmap/user_journeys/engineering"
        - page:
          title: "Design"
          url: "/starmap/user_journeys/design"
     - page:
       title: "Glossary"
       url: "/GLOSSARY"
     - page:
       title: "(drafts)"
       url: "/starmap/specifications/drafts"
       children:
        - page:
          title: "Serialization"
          url: "/starmap/specifications/serialization"
          children:
            - page:
              title: "Transaction"
              url: "/starmap/specifications/runtime/transaction"
              children:
                - page:
                  title: "Feature: target enumeration"
                  url: "/starmap/specifications/runtime/transaction-target-enumeration"
                - page:
                  title: "Feature: optimized"
                  url: "/starmap/specifications/runtime/transaction-optimized"
            - page:
              title: "Plan serialization"
              url: "/starmap/specifications/plan_serialization"
            - page:
              title: "Transaction serialization"
              url: "/starmap/specifications/transaction_serialization"
            - page:
              title: "Life of a serialized transaction"
              url: "/starmap/specifications/life_of_a_serialized_transaction"
        - page:
          title: "Motion demos"
          url: "/starmap/specifications/motion-demos"
          children:
            - page:
              title: "Sparkle dialog"
              url: "/starmap/specifications/motion_demos/sparkle_dialog"
        - page:
          title: "Director composition"
          url: "/starmap/specifications/director_composition"
        - page:
          title: "Condition elements"
          url: "/starmap/specifications/transient_views"
        - page:
          title: "Server"
          url: "/starmap/specifications/server"
        - page:
          title: "Debugging"
          url: "/starmap/specifications/debugging"
        - page:
          title: "REPL"
          url: "/starmap/specifications/repl"
        - page:
          title: "A consultation interface"
          url: "/starmap/specifications/a_consultation_interface"
        - page:
          title: "Applications"
          url: "/starmap/specifications/applications"
        - page:
          title: "Motion Expression"
          url: "/starmap/specifications/expressions"
          children:
            - page:
              title: "Further considerations"
              url: "/starmap/specifications/expressions-addendum"
